# Comment on Pull Request Action

# This action comments on a pull request with a given message.

name: Comment on Pull Request

description: |
  This action comments on a pull request with a given message.

inputs:
  message:
    description: 'The message to post as a comment.'
    required: true

runs:
  using: 'github-script'
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const message = '${{ inputs.message }}';
      const octokit = new Octokit();
      const { data: pullRequest } = await octokit.rest.pulls.get({
        owner: context.repo.owner,
        repo: context.repo.repo,
        pull_number: context.payload.pull_request.number
      });
      await octokit.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: pullRequest.number,
        body: message
      });
