name: Comment

description: 'Comments on pull requests'

inputs:
  pull_request_number:
    description: 'The number of the pull request to comment on'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Comment Linting Issues Action
      run: |
        export GITHUB_TOKEN=$ACTIONS_RUNTIME_TOKEN
        export GITHUB_REPOSITORY=$GITHUB_REPOSITORY
        export GITHUB_WORKFLOW=$GITHUB_WORKFLOW
        export GITHUB_HEAD_REF=$GITHUB_HEAD_REF
        export GITHUB_REF=$GITHUB_REF
        export GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH
        export GITHUB_WORKSPACE=$GITHUB_WORKSPACE
        sh -c "cd $GITHUB_WORKSPACE && node .github/actions/comment-lint-issues/comment-lint-issues.js ${{inputs.pull_request_number}}"
  env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
