# .github/workflows/caller.yml
name: Calling Workflow

on:
  pull_request_target:
    paths:
    - '**.md'
    - '!.github/**'

jobs:
  CallCommenter:
    uses: ./.github/workflows/comment2.yml
    with:
      pr_id: ${{ github.event.number }}
