name: Callable Workflow

on: 
  workflow_call:
    inputs:
      pr_id: 
        description: 'Triggering PR #'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - id: greeting
      run: echo "Triggering PR number ${{ inputs.pr_id }}" >> $GITHUB_STEP_SUMMARY
