# Comment on Pull Request Action

# This action comments on a pull request with a given message.

name: Comment on Pull Request

inputs:
  message:
    description: 'The message to post as a comment.'
    required: true

runs:
  using: 'node16'
  steps:
    - name: Comment on Pull Request
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: '${{ inputs.message }}'
          });
