name: Comment

on:
  workflow_run:
    workflows:
      - Markdown Link Check
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.workflow_run.head_branch}}
      - name: Comment Linting Issues
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require("fs");
            const lintPath = `${process.env.GITHUB_WORKSPACE}/lint.txt`;
            const lintString = fs.readFileSync(lintPath).toString().trimEnd();
            github.rest.issues.createComment({
              issue_number: ${{ github.event.workflow_run.head_commit.message.match(/(?<=\#)\d+(?=\s)/g)[0] }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**The following issues were identified:** \n${lintString}`
            })
