name: Generate Scan Policies from Policy Tags
on: 
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-policies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: zap-admin
    - name: Checkout zap-extensions
      uses: actions/checkout@v4
      with:
        repository: kingthorin/zap-extensions
        persist-credentials: false
        path: zap-extensions
        fetch-depth: 0
    - name: Create Policies
      run: |
        # Run the ZAP script
        docker run -v $(pwd):/zap/wrk/:rw --user root -t ghcr.io/zaproxy/zaproxy:nightly ./zap.sh -addoninstall ascanrulesAlpha -silent -script /zap/wrk/zap-admin/scripts/generate_scan_policies.js -cmd
    - name: Attach Policies
      uses: actions/upload-artifact@v4
      with:
        name: Policies
        path: '*.policy'
    - name: Update Scan Policies
      env:
        GITHUB_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
      run: |
        export BASE=$(pwd)
        # Setup git details
        export GITHUB_USER="github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        BRANCH=scan-policies-updt
        mkdir backup
        cp 'zap-extensions/addOns/scanpolicies/src/main/zapHomeFiles/policies/Default Policy.policy' ./backup/.
        cd zap-extensions
        SRC_BASE="kingthorin/zap-extensions@"$(git log -1 --format=format:%h)
        git checkout -b $BRANCH
        rm ./addOns/scanpolicies/src/main/zapHomeFiles/policies/*.policy
        cp "$BASE/backup/Default policy.policy" ./addOns/scanpolicies/src/main/zapHomeFiles/policies/
        cp $BASE/zap-admin/*.policy ./addOns/scanpolicies/src/main/zapHomeFiles/policies/
        # Update the index to be sure git is aware of changes
        git update-index -q --refresh
        git add ./addOns/scanpolicies/src/main/zapHomeFiles/policies/
        ## If there are changes: comment, commit, PR
        if ! git diff-index --quiet HEAD --; then
          git commit -m "scanpolicies: Update policies based on Tags" -m "Updates based on $SRC_BASE" --signoff
          git push --set-upstream origin $BRANCH --force
          gh pr create -R kingthorin/zap-extensions --fill
        fi
    - name: Summary
      run: |
        cd zap-extensions
        git diff-index
        git diff-index >> $GITHUB_STEP_SUMMARY
        echo $GITHUB_STEP_SUMMARY
