name: Generate API Policy from Policy tags
on: 
  workflow_dispatch:

jobs:
  update-alerts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: zap-admin
    - name: Create list
      run: |
        # Run the ZAP script
        docker run -v $(pwd):/zap/wrk/:rw --user root -t ghcr.io/zaproxy/zaproxy:nightly ./zap.sh -addoninstall ascanrulesAlpha -silent -script /zap/wrk/zap-admin/scripts/generate_scan_policies.js -cmd
    - name: Attach list
      uses: actions/upload-artifact@v4
      with:
        name: APIPolicy
        path: API.policy
    - name: Summary
      run: |
        cat API.policy
        cat API.policy >> $GITHUB_STEP_SUMMARY
        echo $GITHUB_STEP_SUMMARY
